apiVersion: gateway.networking.k8s.io/v1
date: "2026-09-10T14:21:10Z"
gatewayAPIChannel: standard
gatewayAPIVersion: v1.6.2
implementation:
  contact:
  - https://github.com/CleverCloud/sozu-gateway/issues
  organization: clevercloud
  project: sozu-gateway
  url: https://github.com/CleverCloud/sozu-gateway
  version: 9cb7e7f2ba7281520645180cbb46cd20d427454a (clevercloud/sozu:2.2.1)
kind: ConformanceReport
mode: default
profiles:
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 19
      Skipped: 0
  name: GATEWAY-TCP
  summary: Core tests succeeded.
- core:
    result: success
    statistics:
      Failed: 0
      Passed: 20
      Skipped: 0
  name: GATEWAY-UDP
  summary: Core tests succeeded.
- core:
    failedTests:
    - HTTPRouteHeaderMatching
    - HTTPRouteMatching
    - HTTPRouteMatchingAcrossRoutes
    result: failure
    statistics:
      Failed: 3
      Passed: 34
      Skipped: 0
  extended:
    failedTests:
    - HTTPRouteMethodMatching
    result: failure
    statistics:
      Failed: 1
      Passed: 2
      Skipped: 0
    supportedFeatures:
    - HTTPRouteMethodMatching
    - HTTPRouteResponseHeaderModification
    - HTTPRouteSchemeRedirect
    unsupportedFeatures:
    - BackendTLSPolicy
    - BackendTLSPolicySANValidation
    - GatewayAddressEmpty
    - GatewayBackendClientCertificate
    - GatewayFrontendClientCertificateValidation
    - GatewayFrontendClientCertificateValidationInsecureFallback
    - GatewayHTTPListenerIsolation
    - GatewayHTTPSListenerDetectMisdirectedRequests
    - GatewayInfrastructurePropagation
    - GatewayPort8080
    - GatewayStaticAddresses
    - HTTPRoute303RedirectStatusCode
    - HTTPRoute307RedirectStatusCode
    - HTTPRoute308RedirectStatusCode
    - HTTPRouteBackendProtocolH2C
    - HTTPRouteBackendProtocolWebSocket
    - HTTPRouteBackendRequestHeaderModification
    - HTTPRouteBackendTimeout
    - HTTPRouteCORS
    - HTTPRouteDestinationPortMatching
    - HTTPRouteHostRewrite
    - HTTPRouteNamedRouteRule
    - HTTPRouteParentRefPort
    - HTTPRoutePathRedirect
    - HTTPRoutePathRewrite
    - HTTPRoutePortRedirect
    - HTTPRouteQueryParamMatching
    - HTTPRouteRequestMirror
    - HTTPRouteRequestMultipleMirrors
    - HTTPRouteRequestPercentageMirror
    - HTTPRouteRequestTimeout
    - HTTPRouteRetry
    - HTTPRouteRetryBackendTimeout
    - HTTPRouteRetryConnectionError
    - ListenerSet
  name: GATEWAY-HTTP
  summary: Core tests failed with 3 test failures. Extended tests failed with 1 test
    failures.
succeededProvisionalTests:
- TCPRouteInvalidBackendRefNonexistent
- TCPRouteInvalidCrossNamespaceBackendRef
- TCPRouteInvalidNonTCPListener
- TCPRouteParentRefAttachAll
- TCPRouteParentRefPortAndSectionName
- TCPRouteReferenceGrant
- TCPRouteWeightedRouting
- UDPRoute
- UDPRouteInvalidBackendRefNonexistent
- UDPRouteInvalidCrossNamespaceBackendRef
- UDPRouteMultipleRoutesAttachment
- UDPRouteNotAllowedByListeners
- UDPRouteParentRefAttachAllListeners
- UDPRouteParentRefPortAndSectionName
- UDPRouteReferenceGrant
- UDPRouteWeightedRouting
