// WARNING: generated by kopium - manual changes will be overwritten
// kopium command: kopium -f /tmp/crd161/gateways.yaml
// kopium version: 0.24.0

#[allow(unused_imports)]
mod prelude {
    pub use k8s_openapi::apimachinery::pkg::apis::meta::v1::Condition;
    pub use kube::CustomResource;
    pub use serde::{Deserialize, Serialize};
    pub use std::collections::BTreeMap;
}

use self::prelude::*;

#[derive(CustomResource, Serialize, Deserialize, Clone, Debug)]
#[kube(
    group = "gateway.networking.k8s.io",
    version = "v1",
    kind = "Gateway",
    plural = "gateways"
)]
#[kube(namespaced)]
#[kube(status = "GatewayStatus")]
#[kube(schema = "disabled")]
pub struct GatewaySpec {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub addresses: Option<Vec<GatewayAddresses>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "allowedListeners"
    )]
    pub allowed_listeners: Option<GatewayAllowedListeners>,
    #[serde(rename = "gatewayClassName")]
    pub gateway_class_name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub infrastructure: Option<GatewayInfrastructure>,
    pub listeners: Vec<GatewayListeners>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tls: Option<GatewayTls>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayAddresses {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "type")]
    pub r#type: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayAllowedListeners {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub namespaces: Option<GatewayAllowedListenersNamespaces>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayAllowedListenersNamespaces {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub from: Option<GatewayAllowedListenersNamespacesFrom>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub selector: Option<GatewayAllowedListenersNamespacesSelector>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum GatewayAllowedListenersNamespacesFrom {
    All,
    Selector,
    Same,
    None,
    /// A member this build does not know. Kubernetes API enums are open:
    /// a newer CRD may carry values generated before they existed, and a
    /// closed enum would fail the whole list page rather than one object.
    #[serde(other)]
    Unknown,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayAllowedListenersNamespacesSelector {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchExpressions"
    )]
    pub match_expressions: Option<Vec<GatewayAllowedListenersNamespacesSelectorMatchExpressions>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchLabels"
    )]
    pub match_labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayAllowedListenersNamespacesSelectorMatchExpressions {
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayInfrastructure {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub annotations: Option<BTreeMap<String, String>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<BTreeMap<String, String>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "parametersRef"
    )]
    pub parameters_ref: Option<GatewayInfrastructureParametersRef>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayInfrastructureParametersRef {
    pub group: String,
    pub kind: String,
    pub name: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayListeners {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "allowedRoutes"
    )]
    pub allowed_routes: Option<GatewayListenersAllowedRoutes>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub hostname: Option<String>,
    pub name: String,
    pub port: i32,
    pub protocol: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tls: Option<GatewayListenersTls>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayListenersAllowedRoutes {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kinds: Option<Vec<GatewayListenersAllowedRoutesKinds>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub namespaces: Option<GatewayListenersAllowedRoutesNamespaces>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayListenersAllowedRoutesKinds {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
    pub kind: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayListenersAllowedRoutesNamespaces {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub from: Option<GatewayListenersAllowedRoutesNamespacesFrom>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub selector: Option<GatewayListenersAllowedRoutesNamespacesSelector>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum GatewayListenersAllowedRoutesNamespacesFrom {
    All,
    Selector,
    Same,
    /// A member this build does not know. Kubernetes API enums are open:
    /// a newer CRD may carry values generated before they existed, and a
    /// closed enum would fail the whole list page rather than one object.
    #[serde(other)]
    Unknown,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayListenersAllowedRoutesNamespacesSelector {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchExpressions"
    )]
    pub match_expressions:
        Option<Vec<GatewayListenersAllowedRoutesNamespacesSelectorMatchExpressions>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "matchLabels"
    )]
    pub match_labels: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayListenersAllowedRoutesNamespacesSelectorMatchExpressions {
    pub key: String,
    pub operator: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub values: Option<Vec<String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayListenersTls {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "certificateRefs"
    )]
    pub certificate_refs: Option<Vec<GatewayListenersTlsCertificateRefs>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mode: Option<GatewayListenersTlsMode>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub options: Option<BTreeMap<String, String>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayListenersTlsCertificateRefs {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum GatewayListenersTlsMode {
    Terminate,
    Passthrough,
    /// A member this build does not know. Kubernetes API enums are open:
    /// a newer CRD may carry values generated before they existed, and a
    /// closed enum would fail the whole list page rather than one object.
    #[serde(other)]
    Unknown,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayTls {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub backend: Option<GatewayTlsBackend>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub frontend: Option<GatewayTlsFrontend>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayTlsBackend {
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "clientCertificateRef"
    )]
    pub client_certificate_ref: Option<GatewayTlsBackendClientCertificateRef>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayTlsBackendClientCertificateRef {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayTlsFrontend {
    pub default: GatewayTlsFrontendDefault,
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "perPort")]
    pub per_port: Option<Vec<GatewayTlsFrontendPerPort>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayTlsFrontendDefault {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub validation: Option<GatewayTlsFrontendDefaultValidation>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayTlsFrontendDefaultValidation {
    #[serde(rename = "caCertificateRefs")]
    pub ca_certificate_refs: Vec<GatewayTlsFrontendDefaultValidationCaCertificateRefs>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mode: Option<GatewayTlsFrontendDefaultValidationMode>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayTlsFrontendDefaultValidationCaCertificateRefs {
    pub group: String,
    pub kind: String,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum GatewayTlsFrontendDefaultValidationMode {
    AllowValidOnly,
    AllowInsecureFallback,
    /// A member this build does not know. Kubernetes API enums are open:
    /// a newer CRD may carry values generated before they existed, and a
    /// closed enum would fail the whole list page rather than one object.
    #[serde(other)]
    Unknown,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayTlsFrontendPerPort {
    pub port: i32,
    pub tls: GatewayTlsFrontendPerPortTls,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayTlsFrontendPerPortTls {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub validation: Option<GatewayTlsFrontendPerPortTlsValidation>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayTlsFrontendPerPortTlsValidation {
    #[serde(rename = "caCertificateRefs")]
    pub ca_certificate_refs: Vec<GatewayTlsFrontendPerPortTlsValidationCaCertificateRefs>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub mode: Option<GatewayTlsFrontendPerPortTlsValidationMode>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayTlsFrontendPerPortTlsValidationCaCertificateRefs {
    pub group: String,
    pub kind: String,
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub enum GatewayTlsFrontendPerPortTlsValidationMode {
    AllowValidOnly,
    AllowInsecureFallback,
    /// A member this build does not know. Kubernetes API enums are open:
    /// a newer CRD may carry values generated before they existed, and a
    /// closed enum would fail the whole list page rather than one object.
    #[serde(other)]
    Unknown,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub addresses: Option<Vec<GatewayStatusAddresses>>,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "attachedListenerSets"
    )]
    pub attached_listener_sets: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conditions: Option<Vec<Condition>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub listeners: Option<Vec<GatewayStatusListeners>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayStatusAddresses {
    #[serde(default, skip_serializing_if = "Option::is_none", rename = "type")]
    pub r#type: Option<String>,
    pub value: String,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayStatusListeners {
    #[serde(rename = "attachedRoutes")]
    pub attached_routes: i32,
    pub conditions: Vec<Condition>,
    pub name: String,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        rename = "supportedKinds"
    )]
    pub supported_kinds: Option<Vec<GatewayStatusListenersSupportedKinds>>,
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct GatewayStatusListenersSupportedKinds {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub group: Option<String>,
    pub kind: String,
}
